In [42]:
import pandas as pd
df = pd.read_csv('facility_service_data_2022_2024.csv')

print(df)

     facility_id                                   facility_name        state  \
0         FCT012                       Mission Hospital Bwari II          FCT
1         FCT008                 Teaching Hospital Gwagwalada II          FCT
2         NAS006                  PRIMARY HEALTH CENTRE LAFIA II     Nasarawa
3         LAG004            COMPREHENSIVE HEALTH CENTRE SURULERE        Lagos
4         AKS005                Comprehensive Health Centre Oron    Akwa-Ibom
...          ...                                             ...          ...
4409      CRS006      Primary Health Centre Calabar Municipal II  Cross River
4410      AKS013             Model Primary Health Centre Abak II    akwa ibom
4411      KAD012    Comprehensive Health Centre Kaduna South II        Kaduna
4412      NAS001               Model Primary Health Centre Lafia     Nasarawa
4413      RIV009                       Mission Hospital Khana II       Rivers

                    lga report_month hts_tst hts_tst_pos tx_new tx_curr  \
0                 Bwari   30/11/2022     952          39     29   2,721
1            Gwagwalada   30/04/2023     773          40     34    5094
2                 Lafia   2024-01-31     244           6      5     952
3              Surulere   2022-03-31     440           6      4     630
4                  Oron   2022-01-31      76           0      0    1332
...                 ...          ...     ...         ...    ...     ...
4409  Calabar Municipal   2024-08-31     541          19     16    1437
4410               Abak   30/11/2024     306          20     16     722
4411       Kaduna South   2022-04-30     323           3      2     660
4412              Lafia   2022-03-31     128                  1     502
4413              Khana   2024-09-30     544           7      4     764

      tx_ml pmtct_stat  pmtct_stat_pos  pmtct_art tb_screen  tb_pos  \
0        23        300               9          8      2237      36
1        42        102               1          0      2875      41
2        11         58               1          0       526       6
3         8         92               0          0       375       8
4        12         18               1          0       736      19
...     ...        ...             ...        ...       ...     ...
4409     11        128               4          3      1286      21
4410      3         43               2          1       555       8
4411      7         84               3          2       403      11
4412      5         23               0          0       435       8
4413      8         97               2          1       558      21

     vl_eligible vl_result_received vl_suppressed date_submitted  \
0           2271               1624          1396     2022-12-11
1           3722               2467          2342     2023-05-11
2            753                520           476     2024-02-18
3            451                383           358     2022-04-15
4           1145                685           644     2022-02-13
...          ...                ...           ...            ...
4409        1279               1179           968     2024-09-13
4410         520                427           388     2024-12-18
4411         573                316           306     2022-05-13
4412         453                405           380     2022-04-11
4413         661                443           387     2024-10-15

                reported_by
0                Data Clerk
1                Data Clerk
2                Data Clerk
3     Facility Focal Person
4                Data Clerk
...                     ...
4409             Data Clerk
4410             Data Clerk
4411            M&E Officer
4412  Facility Focal Person
4413             Data Clerk

[4414 rows x 20 columns]

In [64]:
import pandas as pd
s = pd.Series([1, 2, 3, 4, 5])

print(s.name)

None

In [65]:
s.name = "calories"

s

0    1
1    2
2    3
3    4
4    5
Name: calories, dtype: int64

In [66]:
#indexing

s[0]

1

In [67]:
s[0:2] # starting values is included ending values is never includeds

0    1
1    2
Name: calories, dtype: int64

In [68]:
#iloc -> location based indexing based on their index

s.iloc[3]

4

In [69]:
s.iloc[[1, 3]]

1    2
3    4
Name: calories, dtype: int64

In [71]:
index = ["apple", "banana", "grapes", "orange", "strawberry"]
s.index = index
print(s)

apple         1
banana        2
grapes        3
orange        4
strawberry    5
Name: calories, dtype: int64

In [73]:
s['grapes']

3

In [ ]:
# loc -> label based indexing  
# In label indexing your start and stop values are always included 
s.loc[['grapes', 'strawberry']]

grapes        3
strawberry    5
Name: calories, dtype: int64

In [81]:
s['apple':'banana']

apple     1
banana    2
Name: calories, dtype: int64

In [92]:
fruit_protein = {
    "Avocado": 2.0,
    "Guava": 2.6,
    "Blackberries": 2.0,
    "Oranges": 0.9,
    "Banana": 1.1,
    "Apple": 0.3,
    "Kiwi": 1.1,
    "Pomagranate": 1.7,
    "Mango": 0.8,
    "Cherries": 1.0 
}

In [93]:
s2 = pd.Series(fruit_protein, name = "Protein")
s2

Avocado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apple           0.3
Kiwi            1.1
Pomagranate     1.7
Mango           0.8
Cherries        1.0
Name: Protein, dtype: float64

In [94]:
s2[s2>1]

Avocado         2.0
Guava           2.6
Blackberries    2.0
Banana          1.1
Kiwi            1.1
Pomagranate     1.7
Name: Protein, dtype: float64

In [99]:
#logical operators AND NOT and OR 

s2[(s2>0.5) | (s2<=2)]

Avocado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apple           0.3
Kiwi            1.1
Pomagranate     1.7
Mango           0.8
Cherries        1.0
Name: Protein, dtype: float64

In [101]:
# not operator
s2[~(s2>1)]

Oranges     0.9
Apple       0.3
Mango       0.8
Cherries    1.0
Name: Protein, dtype: float64

In [104]:
# Modifying the series

s2['Mango'] = 2.8
s2

Avocado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apple           0.3
Kiwi            1.1
Pomagranate     1.7
Mango           2.8
Cherries        1.0
Name: Protein, dtype: float64

In [140]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alcie"],
    "Age": [25, 30, 40, 29, 25, 40],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"],
    "Salary": [50000, 60000, 70000, 62000, 40000, 50000]
}
data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alcie'],
 'Age': [25, 30, 40, 29, 25, 40],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 70000, 62000, 40000, 50000]}

In [141]:
df = pd.DataFrame(data)
df

      Name  Age Department  Salary
0    Alice   25         HR   50000
1      Bob   30         IT   60000
2  Charlie   40    Finance   70000
3    David   29         IT   62000
4      Eve   25         HR   40000
5    Alcie   40         HR   50000

In [142]:
df.head(2)# frist two 
df.tail(3)# last two both in data frame

    Name  Age Department  Salary
3  David   29         IT   62000
4    Eve   25         HR   40000
5  Alcie   40         HR   50000

In [144]:
df.iloc[1:3, :2]

      Name  Age
1      Bob   30
2  Charlie   40

In [145]:
df.loc[1:3, ['Age', 'Department']]

   Age Department
1   30         IT
2   40    Finance
3   29         IT

In [146]:
df[['Age', 'Department']]

   Age Department
0   25         HR
1   30         IT
2   40    Finance
3   29         IT
4   25         HR
5   40         HR

In [ ]:
df.drop("Age", axis = 1)

      Name  Age     Dept  Salary
0    Alice   25       HR   60000
2  Charlie   40  Finance   80000
3    David   29       IT   72000
4      Eve   25       HR   50000
5    Alcie   40       HR   60000

In [148]:
df

      Name  Age Department  Salary
0    Alice   25         HR   50000
1      Bob   30         IT   60000
2  Charlie   40    Finance   70000
3    David   29         IT   62000
4      Eve   25         HR   40000
5    Alcie   40         HR   50000

In [149]:
df.shape

(6, 4)

In [150]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         6 non-null      int64
 2   Department  6 non-null      object
 3   Salary      6 non-null      int64
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

In [151]:
df.describe()

             Age        Salary
count   6.000000      6.000000
mean   31.500000  55333.333333
std     6.892024  10708.252269
min    25.000000  40000.000000
25%    26.000000  50000.000000
50%    29.500000  55000.000000
75%    37.500000  61500.000000
max    40.000000  70000.000000

In [153]:
#Broadcasting
df["Salary"] = df["Salary"] + 5000

df["Salary"]

0    60000
1    70000
2    80000
3    72000
4    50000
5    60000
Name: Salary, dtype: int64

In [158]:
# Renaming columns:

df.rename(columns = {"Department": "Dept"}, inplace = True)
df

      Name  Age     Dept  Salary
0    Alice   25       HR   60000
1      Bob   30       IT   70000
2  Charlie   40  Finance   80000
3    David   29       IT   72000
4      Eve   25       HR   50000
5    Alcie   40       HR   60000

In [161]:
df["Dept"].unique()

array(['HR', 'IT', 'Finance'], dtype=object)

In [163]:
df["Dept"].value_counts()

Dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [167]:
df["Promoted Salary"] = df["Salary"]* 10
df

      Name  Age     Dept  Salary  Promoted Salary
0    Alice   25       HR   60000           600000
1      Bob   30       IT   70000           700000
2  Charlie   40  Finance   80000           800000
3    David   29       IT   72000           720000
4      Eve   25       HR   50000           500000
5    Alcie   40       HR   60000           600000

In [170]:
# Data Cleaning

df.isnull().sum()

Name               0
Age                0
Dept               0
Salary             0
Promoted Salary    0
dtype: int64

In [172]:
# Used to drop Null/NaN values 

df.dropna(how= "all") # Removes row if only all the values are Null/Naa
df.dropna(how="any") # Removes values that have any Null values in a row

      Name  Age     Dept  Salary  Promoted Salary
0    Alice   25       HR   60000           600000
1      Bob   30       IT   70000           700000
2  Charlie   40  Finance   80000           800000
3    David   29       IT   72000           720000
4      Eve   25       HR   50000           500000
5    Alcie   40       HR   60000           600000

In [ ]:
df["Age"].fillna(df["Age"].mean())

      Name  Age     Dept  Salary  Promoted Salary
0    Alice   25       HR   60000           600000
1      Bob   30       IT   70000           700000
2  Charlie   40  Finance   80000           800000
3    David   29       IT   72000           720000
4      Eve   25       HR   50000           500000
5    Alcie   40       HR   60000           600000

In [181]:
df["Salary"].fillna(df["Salary"].median())

0    60000
1    70000
2    80000
3    72000
4    50000
5    60000
Name: Salary, dtype: int64

In [185]:
df["Age"].fillna(method = "bfill")

C:\Users\USER\AppData\Local\Temp\ipykernel_11892\3026805218.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method = "bfill")

0    25
1    30
2    40
3    29
4    25
5    40
Name: Age, dtype: int64

In [189]:
df["Name"].replace("Charlie", "Rose")

0    Alice
1      Bob
2     Rose
3    David
4      Eve
5    Alcie
Name: Name, dtype: object

In [199]:
#  Duplicate values

df = df.drop_duplicates()

In [203]:
# Invalid values
df["Promoted Salary"] = df["Promoted Salary"].apply(lambda x:x/10 if x > 650000 else x )
df

    Name  Age     Dept  Salary  Promoted Salary
0  Alice   25       HR   60000         600000.0
1    Bob   30       IT   70000          70000.0
2   Rose   40  Finance   80000          80000.0
3  David   29       IT   72000          72000.0
4    Eve   25       HR   50000         500000.0
5  Alcie   40       HR   60000         600000.0

In [204]:
name = "alice_fernandes"
df[["first_name", "last_name"]] = df["name"].str.split("")

KeyError: 'name'

In [205]:
# apply and lamda
df["Age"] = df["Age"].apply(lambda x: x/2)

In [206]:
df["Age"] = df["Age"].apply(lambda x:x )