In [3]:
import pandas as pd
df = pd.read_csv('facility_service_data_2022_2024.csv')

df.head(5)

,facility_id,facility_name,state,lga,report_month,hts_tst,hts_tst_pos,tx_new,tx_curr,tx_ml,pmtct_stat,pmtct_stat_pos,pmtct_art,tb_screen,tb_pos,vl_eligible,vl_result_received,vl_suppressed,date_submitted,reported_by
0,FCT012,Mission Hospital Bwari II,FCT,Bwari,30/11/2022,952,39,29,"2,721",23,300,9,8,2237,36,2271,1624,1396,2022-12-11,Data Clerk
1,FCT008,Teaching Hospital Gwagwalada II,FCT,Gwagwalada,30/04/2023,773,40,34,5094,42,102,1,0,2875,41,3722,2467,2342,2023-05-11,Data Clerk
2,NAS006,PRIMARY HEALTH CENTRE LAFIA II,Nasarawa,Lafia,2024-01-31,244,6,5,952,11,58,1,0,526,6,753,520,476,2024-02-18,Data Clerk
3,LAG004,COMPREHENSIVE HEALTH CENTRE SURULERE,Lagos,Surulere,2022-03-31,440,6,4,630,8,92,0,0,375,8,451,383,358,2022-04-15,Facility Focal Person
4,AKS005,Comprehensive Health Centre Oron,Akwa-Ibom,Oron,2022-01-31,76,0,0,1332,12,18,1,0,736,19,1145,685,644,2022-02-13,Data Clerk

In [9]:
cols = ["facility_id", "facility_name", "state", "lga"]
df[cols] = df[cols].apply(
    lambda col: col.str.strip().str.upper()
)
df

,facility_id,facility_name,state,lga,report_month,hts_tst,hts_tst_pos,tx_new,tx_curr,tx_ml,pmtct_stat,pmtct_stat_pos,pmtct_art,tb_screen,tb_pos,vl_eligible,vl_result_received,vl_suppressed,date_submitted,reported_by
0,FCT012,MISSION HOSPITAL BWARI II,FCT,BWARI,30/11/2022,952,39,29,"2,721",23,300,9,8,2237,36,2271,1624,1396,2022-12-11,Data Clerk
1,FCT008,TEACHING HOSPITAL GWAGWALADA II,FCT,GWAGWALADA,30/04/2023,773,40,34,5094,42,102,1,0,2875,41,3722,2467,2342,2023-05-11,Data Clerk
2,NAS006,PRIMARY HEALTH CENTRE LAFIA II,NASARAWA,LAFIA,2024-01-31,244,6,5,952,11,58,1,0,526,6,753,520,476,2024-02-18,Data Clerk
3,LAG004,COMPREHENSIVE HEALTH CENTRE SURULERE,LAGOS,SURULERE,2022-03-31,440,6,4,630,8,92,0,0,375,8,451,383,358,2022-04-15,Facility Focal Person
4,AKS005,COMPREHENSIVE HEALTH CENTRE ORON,AKWA-IBOM,ORON,2022-01-31,76,0,0,1332,12,18,1,0,736,19,1145,685,644,2022-02-13,Data Clerk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4409,CRS006,PRIMARY HEALTH CENTRE CALABAR MUNICIPAL II,CROSS RIVER,CALABAR MUNICIPAL,2024-08-31,541,19,16,1437,11,128,4,3,1286,21,1279,1179,968,2024-09-13,Data Clerk
4410,AKS013,MODEL PRIMARY HEALTH CENTRE ABAK II,AKWA IBOM,ABAK,30/11/2024,306,20,16,722,3,43,2,1,555,8,520,427,388,2024-12-18,Data Clerk
4411,KAD012,COMPREHENSIVE HEALTH CENTRE KADUNA SOUTH II,KADUNA,KADUNA SOUTH,2022-04-30,323,3,2,660,7,84,3,2,403,11,573,316,306,2022-05-13,M&E Officer
4412,NAS001,MODEL PRIMARY HEALTH CENTRE LAFIA,NASARAWA,LAFIA,2022-03-31,128,,1,502,5,23,0,0,435,8,453,405,380,2022-04-11,Facility Focal Person
4413,RIV009,MISSION HOSPITAL KHANA II,RIVERS,KHANA,2024-09-30,544,7,4,764,8,97,2,1,558,21,661,443,387,2024-10-15,Data Clerk

In [ ]:
cols = ["report_month", "date_submitted"]

df[cols] = df[cols].apply(
    lambda col:pd.to_datetime(cols, error= "coerce")
)

AttributeError: 'Series' object has no attribute 'pd'