In [974]:
# Imported the csv file 
import pandas as pd
df = pd.read_csv('facility_service_data_2022_2024.csv')

df.head(5)

,facility_id,facility_name,state,lga,report_month,hts_tst,hts_tst_pos,tx_new,tx_curr,tx_ml,pmtct_stat,pmtct_stat_pos,pmtct_art,tb_screen,tb_pos,vl_eligible,vl_result_received,vl_suppressed,date_submitted,reported_by
0,FCT012,Mission Hospital Bwari II,FCT,Bwari,30/11/2022,952,39,29,"2,721",23,300,9,8,2237,36,2271,1624,1396,2022-12-11,Data Clerk
1,FCT008,Teaching Hospital Gwagwalada II,FCT,Gwagwalada,30/04/2023,773,40,34,5094,42,102,1,0,2875,41,3722,2467,2342,2023-05-11,Data Clerk
2,NAS006,PRIMARY HEALTH CENTRE LAFIA II,Nasarawa,Lafia,2024-01-31,244,6,5,952,11,58,1,0,526,6,753,520,476,2024-02-18,Data Clerk
3,LAG004,COMPREHENSIVE HEALTH CENTRE SURULERE,Lagos,Surulere,2022-03-31,440,6,4,630,8,92,0,0,375,8,451,383,358,2022-04-15,Facility Focal Person
4,AKS005,Comprehensive Health Centre Oron,Akwa-Ibom,Oron,2022-01-31,76,0,0,1332,12,18,1,0,736,19,1145,685,644,2022-02-13,Data Clerk

In [975]:
# Changed the facility name, id's, state, and lga to uppercase.
df['state'] = df['state'].str.strip().str.upper()
df['facility_name'] = df['facility_name'].str.strip().str.upper()
df['facility_id'] = df['facility_id'].str.strip().str.upper()
df['lga'] = df['lga'].str.strip().str.upper()
df

,facility_id,facility_name,state,lga,report_month,hts_tst,hts_tst_pos,tx_new,tx_curr,tx_ml,pmtct_stat,pmtct_stat_pos,pmtct_art,tb_screen,tb_pos,vl_eligible,vl_result_received,vl_suppressed,date_submitted,reported_by
0,FCT012,MISSION HOSPITAL BWARI II,FCT,BWARI,30/11/2022,952,39,29,"2,721",23,300,9,8,2237,36,2271,1624,1396,2022-12-11,Data Clerk
1,FCT008,TEACHING HOSPITAL GWAGWALADA II,FCT,GWAGWALADA,30/04/2023,773,40,34,5094,42,102,1,0,2875,41,3722,2467,2342,2023-05-11,Data Clerk
2,NAS006,PRIMARY HEALTH CENTRE LAFIA II,NASARAWA,LAFIA,2024-01-31,244,6,5,952,11,58,1,0,526,6,753,520,476,2024-02-18,Data Clerk
3,LAG004,COMPREHENSIVE HEALTH CENTRE SURULERE,LAGOS,SURULERE,2022-03-31,440,6,4,630,8,92,0,0,375,8,451,383,358,2022-04-15,Facility Focal Person
4,AKS005,COMPREHENSIVE HEALTH CENTRE ORON,AKWA-IBOM,ORON,2022-01-31,76,0,0,1332,12,18,1,0,736,19,1145,685,644,2022-02-13,Data Clerk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4409,CRS006,PRIMARY HEALTH CENTRE CALABAR MUNICIPAL II,CROSS RIVER,CALABAR MUNICIPAL,2024-08-31,541,19,16,1437,11,128,4,3,1286,21,1279,1179,968,2024-09-13,Data Clerk
4410,AKS013,MODEL PRIMARY HEALTH CENTRE ABAK II,AKWA IBOM,ABAK,30/11/2024,306,20,16,722,3,43,2,1,555,8,520,427,388,2024-12-18,Data Clerk
4411,KAD012,COMPREHENSIVE HEALTH CENTRE KADUNA SOUTH II,KADUNA,KADUNA SOUTH,2022-04-30,323,3,2,660,7,84,3,2,403,11,573,316,306,2022-05-13,M&E Officer
4412,NAS001,MODEL PRIMARY HEALTH CENTRE LAFIA,NASARAWA,LAFIA,2022-03-31,128,,1,502,5,23,0,0,435,8,453,405,380,2022-04-11,Facility Focal Person
4413,RIV009,MISSION HOSPITAL KHANA II,RIVERS,KHANA,2024-09-30,544,7,4,764,8,97,2,1,558,21,661,443,387,2024-10-15,Data Clerk

In [976]:
# Some states has two different spelling so i had to change them to just one
df["state"] = (
    df["state"].str.strip().str.upper().replace({
        "FCT": "FCT",
        "FEDERAL CAPITAL TERRITORY": "FCT",
        'F.C.T.': "FCT",
        "CROSS-RIVER": "CROSS RIVER",
        "AKWA-IBOM": "AKWA IBOM"
    })
)

df["state"].value_counts()

state
RIVERS         560
LAGOS          556
BENUE          555
KADUNA         553
NASARAWA       550
FCT            547
AKWA IBOM      547
CROSS RIVER    546
Name: count, dtype: int64

In [977]:
# Changed the dated to pandas date and time format
cols = ["report_month", "date_submitted"]

df[cols] = df[cols].apply(
    lambda col: pd.to_datetime(col, format="mixed" ,errors="coerce")
)
df[cols]

     report_month date_submitted
0      2022-11-30     2022-12-11
1      2023-04-30     2023-05-11
2      2024-01-31     2024-02-18
3      2022-03-31     2022-04-15
4      2022-01-31     2022-02-13
...           ...            ...
4409   2024-08-31     2024-09-13
4410   2024-11-30     2024-12-18
4411   2022-04-30     2022-05-13
4412   2022-03-31     2022-04-11
4413   2024-09-30     2024-10-15

[4414 rows x 2 columns]

In [978]:
# Created a seperate column for year, month and quarter
df['year'] = df['report_month'].dt.year
df['month'] = df['report_month'].dt.month
df['quarter'] = df['report_month'].dt.quarter
df

,facility_id,facility_name,state,lga,report_month,hts_tst,hts_tst_pos,tx_new,tx_curr,tx_ml,...,tb_screen,tb_pos,vl_eligible,vl_result_received,vl_suppressed,date_submitted,reported_by,year,month,quarter
0,FCT012,MISSION HOSPITAL BWARI II,FCT,BWARI,2022-11-30,952,39,29,"2,721",23,...,2237,36,2271,1624,1396,2022-12-11,Data Clerk,2022,11,4
1,FCT008,TEACHING HOSPITAL GWAGWALADA II,FCT,GWAGWALADA,2023-04-30,773,40,34,5094,42,...,2875,41,3722,2467,2342,2023-05-11,Data Clerk,2023,4,2
2,NAS006,PRIMARY HEALTH CENTRE LAFIA II,NASARAWA,LAFIA,2024-01-31,244,6,5,952,11,...,526,6,753,520,476,2024-02-18,Data Clerk,2024,1,1
3,LAG004,COMPREHENSIVE HEALTH CENTRE SURULERE,LAGOS,SURULERE,2022-03-31,440,6,4,630,8,...,375,8,451,383,358,2022-04-15,Facility Focal Person,2022,3,1
4,AKS005,COMPREHENSIVE HEALTH CENTRE ORON,AKWA IBOM,ORON,2022-01-31,76,0,0,1332,12,...,736,19,1145,685,644,2022-02-13,Data Clerk,2022,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4409,CRS006,PRIMARY HEALTH CENTRE CALABAR MUNICIPAL II,CROSS RIVER,CALABAR MUNICIPAL,2024-08-31,541,19,16,1437,11,...,1286,21,1279,1179,968,2024-09-13,Data Clerk,2024,8,3
4410,AKS013,MODEL PRIMARY HEALTH CENTRE ABAK II,AKWA IBOM,ABAK,2024-11-30,306,20,16,722,3,...,555,8,520,427,388,2024-12-18,Data Clerk,2024,11,4
4411,KAD012,COMPREHENSIVE HEALTH CENTRE KADUNA SOUTH II,KADUNA,KADUNA SOUTH,2022-04-30,323,3,2,660,7,...,403,11,573,316,306,2022-05-13,M&E Officer,2022,4,2
4412,NAS001,MODEL PRIMARY HEALTH CENTRE LAFIA,NASARAWA,LAFIA,2022-03-31,128,,1,502,5,...,435,8,453,405,380,2022-04-11,Facility Focal Person,2022,3,1
4413,RIV009,MISSION HOSPITAL KHANA II,RIVERS,KHANA,2024-09-30,544,7,4,764,8,...,558,21,661,443,387,2024-10-15,Data Clerk,2024,9,3

In [979]:
# Moved the year, month and quarter column from the end to just beside the report_month column from better reading
cols = df.columns.tolist()
cols.remove('year')
cols.remove('month')
cols.remove('quarter')

cols.insert(5, 'year')
cols.insert(6, 'month')
cols.insert(7, 'quarter')
df = df[cols]
df.tail(3)

,facility_id,facility_name,state,lga,report_month,year,month,quarter,hts_tst,hts_tst_pos,...,pmtct_stat,pmtct_stat_pos,pmtct_art,tb_screen,tb_pos,vl_eligible,vl_result_received,vl_suppressed,date_submitted,reported_by
4411,KAD012,COMPREHENSIVE HEALTH CENTRE KADUNA SOUTH II,KADUNA,KADUNA SOUTH,2022-04-30,2022,4,2,323,3,...,84,3,2,403,11,573,316,306,2022-05-13,M&E Officer
4412,NAS001,MODEL PRIMARY HEALTH CENTRE LAFIA,NASARAWA,LAFIA,2022-03-31,2022,3,1,128,,...,23,0,0,435,8,453,405,380,2022-04-11,Facility Focal Person
4413,RIV009,MISSION HOSPITAL KHANA II,RIVERS,KHANA,2024-09-30,2024,9,3,544,7,...,97,2,1,558,21,661,443,387,2024-10-15,Data Clerk

In [980]:
# validating the dates to make sure they fall under 2022 - 2024 and end of the month 
valid_dates = (
    df["report_month"].dt.year.between(2022, 2024)
    & df["report_month"].dt.is_month_end
)

df.loc[~valid_dates, "report_month"]

5      2022-05-01
10     2024-06-01
11     2023-02-01
24     2022-12-01
38     2024-12-01
          ...
4382   2023-01-01
4383   2022-03-01
4394   2024-12-01
4399   2023-12-01
4406   2023-11-01
Name: report_month, Length: 441, dtype: datetime64[ns]

In [981]:
# Replaced ["", "N/A", "-", 'NULL', "nil"] with pandas NA
df.replace(["", "N/A", "-", 'NULL', "nil"], pd.NA, inplace= True)

In [982]:
df.head()

,facility_id,facility_name,state,lga,report_month,year,month,quarter,hts_tst,hts_tst_pos,...,pmtct_stat,pmtct_stat_pos,pmtct_art,tb_screen,tb_pos,vl_eligible,vl_result_received,vl_suppressed,date_submitted,reported_by
0,FCT012,MISSION HOSPITAL BWARI II,FCT,BWARI,2022-11-30,2022,11,4,952,39,...,300,9,8,2237,36,2271,1624,1396,2022-12-11,Data Clerk
1,FCT008,TEACHING HOSPITAL GWAGWALADA II,FCT,GWAGWALADA,2023-04-30,2023,4,2,773,40,...,102,1,0,2875,41,3722,2467,2342,2023-05-11,Data Clerk
2,NAS006,PRIMARY HEALTH CENTRE LAFIA II,NASARAWA,LAFIA,2024-01-31,2024,1,1,244,6,...,58,1,0,526,6,753,520,476,2024-02-18,Data Clerk
3,LAG004,COMPREHENSIVE HEALTH CENTRE SURULERE,LAGOS,SURULERE,2022-03-31,2022,3,1,440,6,...,92,0,0,375,8,451,383,358,2022-04-15,Facility Focal Person
4,AKS005,COMPREHENSIVE HEALTH CENTRE ORON,AKWA IBOM,ORON,2022-01-31,2022,1,1,76,0,...,18,1,0,736,19,1145,685,644,2022-02-13,Data Clerk

In [983]:
# Removed commas white spaces and convertes all the numbers from text to number 
cols = ["hts_tst", "hts_tst_pos", "tx_new", "tx_curr", "tx_ml", "pmtct_stat", "pmtct_stat_pos", "pmtct_art", "tb_screen", "tb_pos", "vl_eligible", "vl_result_received", "vl_suppressed"]

df[cols] = (df[cols].replace(",", "")
    .apply(lambda col: col.astype("string").str.strip())
    .apply(pd.to_numeric, errors="coerce"))

In [984]:
# Checking for negative values
negative_values = df[
    (df[cols] < 0).any(axis=1)
]

negative_values.head()

,facility_id,facility_name,state,lga,report_month,year,month,quarter,hts_tst,hts_tst_pos,...,pmtct_stat,pmtct_stat_pos,pmtct_art,tb_screen,tb_pos,vl_eligible,vl_result_received,vl_suppressed,date_submitted,reported_by
46,RIV010,TEACHING HOSPITAL AHOADA EAST II,RIVERS,AHOADA EAST,2022-06-30,2022,6,2,756.0,11.0,...,174.0,4,3,2272.0,48,3052.0,2439.0,2092.0,2022-07-21,M&E Officer
113,AKS009,PRIMARY HEALTH CENTRE IKOT EKPENE II,AKWA IBOM,IKOT EKPENE,2024-07-31,2024,7,3,109.0,6.0,...,27.0,1,0,137.0,2,190.0,145.0,135.0,2024-08-21,Data Clerk
339,AKS005,COMPREHENSIVE HEALTH CENTRE ORON,AKWA IBOM,ORON,2022-09-30,2022,9,3,127.0,0.0,...,27.0,0,0,1123.0,22,1113.0,687.0,649.0,2022-10-13,Facility Focal Person
510,BEN015,PRIMARY HEALTH CENTRE OTUKPO II,BENUE,OTUKPO,2022-07-31,2022,7,3,1440.0,3.0,...,18.0,0,0,764.0,9,733.0,605.0,526.0,2022-08-16,M&E Officer
582,LAG012,PRIMARY HEALTH CENTRE ALIMOSHO II,LAGOS,ALIMOSHO,2024-07-31,2024,7,3,382.0,18.0,...,82.0,1,0,597.0,7,597.0,474.0,445.0,2024-08-16,Facility Focal Person

In [985]:
# checked the number of duplicates in the dataset
df.duplicated().sum()

59

In [986]:
# Removed duplicates from the dataset
df = df.drop_duplicates(keep="first")

In [987]:
# Checking how many null values in each column
df.isna().sum()

facility_id             0
facility_name           0
state                   0
lga                     0
report_month            0
year                    0
month                   0
quarter                 0
hts_tst                77
hts_tst_pos            78
tx_new                 76
tx_curr               139
tx_ml                   0
pmtct_stat             77
pmtct_stat_pos          0
pmtct_art               0
tb_screen              79
tb_pos                  0
vl_eligible            78
vl_result_received     77
vl_suppressed          76
date_submitted          0
reported_by             0
dtype: int64

In [988]:
# Working on the facility master list
fm= pd.read_csv("facility_master_list.csv")
fm.head(5)

,facility_id,facility_name,state,lga,facility_level,ownership,setting,art_start_date,catchment_population,latitude,longitude
0,AKS001,Comprehensive Health Centre Uyo,Akwa Ibom,Uyo,Primary,Private,Urban,2015-04-22,79792.0,10.09626,9.47271
1,AKS002,General Hospital Ikot Ekpene,Akwa Ibom,Ikot Ekpene,Secondary,Public,Urban,2013-09-22,49951.0,7.01753,4.10253
2,AKS003,Model Primary Health Centre Eket,Akwa Ibom,Eket,Primary,Public,Rural,2022-04-04,32449.0,8.46012,3.03009
3,AKS004,Comprehensive Health Centre Etinan,Akwa Ibom,Etinan,Primary,Public,Rural,2018-09-03,193467.0,8.67776,5.11477
4,AKS005,Comprehensive Health Centre Oron,Akwa Ibom,Oron,Primary,Public,Rural,2020-08-04,72505.0,10.62470,4.38552

In [989]:
#Infor about that csv file
fm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126 entries, 0 to 125
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   facility_id           126 non-null    object
 1   facility_name         126 non-null    object
 2   state                 126 non-null    object
 3   lga                   126 non-null    object
 4   facility_level        126 non-null    object
 5   ownership             120 non-null    object
 6   setting               120 non-null    object
 7   art_start_date        126 non-null    object
 8   catchment_population  120 non-null    float64
 9   latitude              126 non-null    float64
 10  longitude             126 non-null    float64
dtypes: float64(3), object(8)
memory usage: 11.0+ KB

In [1078]:
#Checking for unique values
fm["facility_id"].is_unique

True

In [1079]:
# checking duplicates from fm
master_duplicates = fm[
    fm["facility_id"].duplicated(keep=False)
]

master_duplicates

Empty DataFrame
Columns: [facility_id, facility_name, state, lga, facility_level, ownership, setting, art_start_date, catchment_population, latitude, longitude]
Index: []

In [1080]:
# checking if the facility id 
fm["facility_id"].head()

0    AKS001
1    AKS002
2    AKS003
3    AKS004
4    AKS005
Name: facility_id, dtype: string

In [1081]:
# checking how many missing values exist
fm.isna().sum()

facility_id             0
facility_name           0
state                   0
lga                     0
facility_level          0
ownership               6
setting                 6
art_start_date          0
catchment_population    6
latitude                0
longitude               0
dtype: int64

In [994]:
# Removing duplicates from fm
fm.drop_duplicates(subset=["facility_id"], keep="first", inplace=True)

In [995]:
# Standardizing the facility id 
fm["facility_id"] = (fm["facility_id"].astype("string").str.strip().str.upper())

In [996]:
# Merging the facility id on both the facility master file and the facility service data 
merged = df.merge(
    fm,
    on="facility_id",
    how="outer",
    indicator=True
)

In [1101]:
merged.columns

Index(['facility_id', 'facility_name_x', 'state_x', 'lga_x', 'report_month',
       'year', 'month', 'quarter', 'hts_tst', 'hts_tst_pos', 'tx_new',
       'tx_curr', 'tx_ml', 'pmtct_stat', 'pmtct_stat_pos', 'pmtct_art',
       'tb_screen', 'tb_pos', 'vl_eligible', 'vl_result_received',
       'vl_suppressed', 'date_submitted', 'reported_by', 'facility_name_y',
       'state_y', 'lga_y', 'facility_level', 'ownership', 'setting',
       'art_start_date', 'catchment_population', 'latitude', 'longitude',
       '_merge'],
      dtype='object')

In [997]:
# Checking the merge outcome
merged["_merge"].value_counts()

_merge
both          4175
left_only      180
right_only       5
Name: count, dtype: int64

In [1082]:
# checking the merge on the left
fmna = merged[
    merged["_merge"] == "left_only"
]
fmna.head()

,facility_id,facility_name_x,state_x,lga_x,report_month,year,month,quarter,hts_tst,hts_tst_pos,...,state_y,lga_y,facility_level,ownership,setting,art_start_date,catchment_population,latitude,longitude,_merge
1433,LAG099,GENERAL HOSPITAL CHIKUN II,KADUNA,CHIKUN,2024-05-31,2024.0,5.0,2.0,361.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1434,LAG099,SPECIALIST HOSPITAL ALIMOSHO,LAGOS,ALIMOSHO,2023-05-31,2023.0,5.0,2.0,1093.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1435,LAG099,MODEL PRIMARY HEALTH CENTRE KADUNA NORTH,KADUNA,KADUNA NORTH,2023-04-30,2023.0,4.0,2.0,251.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1436,LAG099,COTTAGE HOSPITAL GWAGWALADA II,FCT,GWAGWALADA,2024-06-30,2024.0,6.0,2.0,1377.0,19.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1437,LAG099,MODEL PRIMARY HEALTH CENTRE KATSINA-ALA II,BENUE,KATSINA-ALA,2023-04-30,2023.0,4.0,2.0,255.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [999]:
# checking the merge on the right
fmnaa = merged[
    merged["_merge"] == "right_only"
]
fmnaa

,facility_id,facility_name_x,state_x,lga_x,report_month,year,month,quarter,hts_tst,hts_tst_pos,...,state_y,lga_y,facility_level,ownership,setting,art_start_date,catchment_population,latitude,longitude,_merge
4355,NEW001,NaN,NaN,NaN,NaT,NaN,NaN,NaN,<NA>,<NA>,...,Cross River,Obudu,Primary,Private,Urban,2018-08-05,155505.0,11.31909,9.02246,right_only
4356,NEW002,NaN,NaN,NaN,NaT,NaN,NaN,NaN,<NA>,<NA>,...,Cross River,Calabar Municipal,Primary,Public,Rural,2020-03-08,195430.0,9.40478,3.56223,right_only
4357,NEW003,NaN,NaN,NaN,NaT,NaN,NaN,NaN,<NA>,<NA>,...,Akwa Ibom,Abak,Primary,Public,Rural,2016-08-10,70260.0,6.37644,3.46073,right_only
4358,NEW004,NaN,NaN,NaN,NaT,NaN,NaN,NaN,<NA>,<NA>,...,Nasarawa,Karu,Secondary,Private,Urban,2014-08-25,197190.0,9.05993,7.19223,right_only
4359,NEW005,NaN,NaN,NaN,NaT,NaN,NaN,NaN,<NA>,<NA>,...,Cross River,Ikom,Primary,Public,Rural,2017-10-18,46195.0,5.01068,5.08764,right_only

In [1000]:
#Cross checking
df.shape

(4355, 23)

In [1001]:
#Cross checking
df.columns

Index(['facility_id', 'facility_name', 'state', 'lga', 'report_month', 'year',
       'month', 'quarter', 'hts_tst', 'hts_tst_pos', 'tx_new', 'tx_curr',
       'tx_ml', 'pmtct_stat', 'pmtct_stat_pos', 'pmtct_art', 'tb_screen',
       'tb_pos', 'vl_eligible', 'vl_result_received', 'vl_suppressed',
       'date_submitted', 'reported_by'],
      dtype='object')

In [1083]:
# checkingb the datatypes of the report month and date submitted
df[["report_month", "date_submitted"]].dtypes

report_month      datetime64[ns]
date_submitted    datetime64[ns]
dtype: object

In [1003]:
# Creating a list of all the columns i want to work with for the validation fucntions 
lists = [
    "hts_tst",
    "hts_tst_pos",
    "tx_new",
    "tx_curr",
    "tx_ml",
    "pmtct_stat",
    "pmtct_stat_pos",
    "pmtct_art",
    "tb_screen",
    "tb_pos",
    "vl_eligible",
    "vl_result_received",
    "vl_suppressed"
]

In [1004]:
# This function creates a table with the rows that faild the validation 
def make_issue(df, mask, rule_id, description, observed):
    result = df.loc[
        mask,
        ["facility_id", "report_month"]
    ].copy()

    result["rule_id"] = rule_id
    result["description"] = description
    result["observed"] = observed.loc[mask].astype("string")

    return result[
        ["facility_id", "report_month", "rule_id", "description", "observed"]
    ]

In [1005]:
# function that makes sure hts_tst_pos <= hts_tst
def r1(df):
    mask = (
        df["hts_tst_pos"].notna() &
        df["hts_tst"].notna() & (df["hts_tst_pos"] > df["hts_tst"])
    )

    observed = (
        df["hts_tst_pos"].astype("string")+ " > " +df["hts_tst"].astype("string")
    )

    return make_issue(
        df,
        mask,
        "R1",
        "hts_tst_pos must be less than or equal to hts_tst",
        observed
    )

In [1006]:
# this function	checks if pmtct_stat_pos <= pmtct_stat, and pmtct_art <= pmtct_stat_pos
def r2(df):
    condition_1 = (
        df["pmtct_stat_pos"].notna() &
        df["pmtct_stat"].notna() &
        (df["pmtct_stat_pos"] > df["pmtct_stat"])
    )

    condition_2 = (
        df["pmtct_art"].notna() &
        df["pmtct_stat_pos"].notna() &
      (df["pmtct_art"] > df["pmtct_stat_pos"])
    )

    mask = condition_1 | condition_2

    observed = (
        "pmtct_stat_pos=" + df["pmtct_stat_pos"].astype("string") +
        ", pmtct_stat=" + df["pmtct_stat"].astype("string") +
        ", pmtct_art=" + df["pmtct_art"].astype("string")
    )

    return make_issue(
        df,
        mask,
        "R2",
        "PMTCT cascade relationship is invalid",
        observed
    )

In [1007]:
# r3 validates that vl_result_received should be <= vl_eligible, and vl_suppressed should be <= vl_result_received
def r3(df):
    condition_1 = (
        df["vl_result_received"].notna() &
        df["vl_eligible"].notna() &
        (df["vl_result_received"] > df["vl_eligible"])
    )

    condition_2 = (
        df["vl_suppressed"].notna() &
        df["vl_result_received"].notna() &
        (df["vl_suppressed"] > df["vl_result_received"])
    )

    mask = condition_1 | condition_2

    observed = (
        "vl_eligible=" + df["vl_eligible"].astype("string") +
        ", vl_result_received=" + df["vl_result_received"].astype("string") +", vl_suppressed=" + df["vl_suppressed"].astype("string")
    )

    return make_issue(
        df,
        mask,
        "R3",
        "Viral load cascade relationship is invalid",
        observed
    )

In [1008]:
# r4 checks if tb_pos <= tb_screen.	Same logic as r1, r2 and r3.
def r4(df):
    mask = (
        df["tb_pos"].notna() &
        df["tb_screen"].notna() &
        (df["tb_pos"] > df["tb_screen"])
    )

    observed = (
        df["tb_pos"].astype("string")
        + " > " +
        df["tb_screen"].astype("string")
    )

    return make_issue(
        df,
        mask,
        "R4",
        "tb_pos must be less than or equal to tb_screen",
        observed
    )

In [1009]:
# r5 checks for values in the list array that is less than 0
def r5(df):
    mask = df[lists].lt(0).any(axis=1)

    observed = df[lists].where(df[lists].lt(0)).apply(
        lambda row: row.dropna().to_dict(), axis=1).astype("string")

    return make_issue(
        df,
        mask,
        "R5",
        "Negative values are not allowed",
        observed
    )

In [1010]:
# r6 check if positivity yield is between 0.1% and 15%
def r6(df):
    valid = (
        df["hts_tst"].notna() &
        df["hts_tst_pos"].notna() &
        (df["hts_tst"] > 0) 
    )

    yield_pct = (
        df["hts_tst_pos"] / df["hts_tst"] * 100
    )

    mask = valid & (
        (yield_pct < 0.1) | (yield_pct > 15)
    )

    observed = yield_pct.round(2).astype("string") + "%"

    return make_issue(
        df, 
        mask,
        "R6",
        "HTS positively yield must be between 0.1%, and 15%",
        observed
    )

In [1011]:
# hts_tst month change in hts_tst that is under 300%
def r7(df):
    previous = (
        df.groupby("facility_id")
        ["hts_tst"].shift(1)
    )

    valid = (
        df["hts_tst"].notna() &
        previous.notna() &
        (previous > 0)
    )

    change_pct = (
        (df["hts_tst"] - previous).abs()
        /previous * 100)

    mask = valid & (change_pct >= 300)

    observed = change_pct.round(2).astype("string") + "% change"

    return make_issue(
        df, 
        mask,
        "R7",
        "Month-on-month change in hts_tst must be under 300%",
        observed
    )

In [1012]:
# r8 check if each facility has 36 report_months 
def r8(df):
    count = (
        df.groupby("facility_id")
        ["report_month"].nunique()
    )

    incomplete_facilities = count[count != 36]

    mask = df["facility_id"].isin(
        incomplete_facilities.index
    )

    observed = (
        df["facility_id"].map(count).astype("string")+ "/36 monthly records"
    )

    return make_issue(
        df, 
        mask, 
        "R8",
        "Each facility should have 36 monthly recodrs",
        observed
    )

In [1013]:
# the date submitted must be after the reporting month has ended
def r9(df):
    mask = (
        df["date_submitted"].notna()&
        df["report_month"].notna()&
        (df["date_submitted"] <= df["report_month"])
    )

    observed = (
        "submitted=" +
        df["date_submitted"].astype("string") + ", period_end=" + df["report_month"].astype("string")
    )

    return make_issue(
        df,
        mask,
        "R9",
        "date_submitted must be after the reporting period end",
        observed
    )

In [1014]:
# the date submitted must be wthin 15 days of the report month ending
def r10(df):
    day_late = (
        df["date_submitted"] - df["report_month"]
    ).dt.days

    mask = (
        df["date_submitted"].notna()&
        df["report_month"].notna()&
        (day_late > 15)
    )

    observed = (
        day_late.astype("string") + " days"
    )

    return make_issue(
        df,
        mask,
        "R10",
        "Report should be submitted within 15 days of period end",
        observed
    )

In [1015]:
# It check if the current tx is eqaul to the expected current tx
def r11(df):
    previous_tx_curr = (
        df.groupby("facility_id")["tx_curr"].shift(1)
    )

    expected_tx_curr = (
        previous_tx_curr + df["tx_new"]- df["tx_ml"]
    )

    valid = (
        previous_tx_curr.notna()& df["tx_curr"].notna()& df["tx_ml"].notna()& df["tx_new"].notna()
    )

    mask = valid & (
        df["tx_curr"] != expected_tx_curr
    )

    observed = (
        "actual=" + df["tx_curr"].astype("string") + ", expected=" + expected_tx_curr.astype("string")
    )

    return make_issue(
        df, 
        mask,
        "R11",
        "tx_curr should approximately equal previous tx_curr + tx_new - tx_ml",
        observed
    )

In [1016]:
# this basically stacks the function results and prints on issues dataframe
issues = pd.concat(
    [           # Data-quality Dimensions
        r1(df), #Consistency/Integrity
        r2(df), #Consistency/ Integrity
        r3(df), # Consistency/Integrity
        r4(df), # Consistency/Integrity
        r5(df), # Integrity
        r6(df), # Accuracy
        r7(df), # Accuracy
        r8(df), # Completness
        r9(df), # Timeliness
        r10(df),# Timeliness
        r11(df) #Integrity / Consistency
    ],
    ignore_index= True
)

In [1017]:
# checking the issues df
issues.head()

,facility_id,report_month,rule_id,description,observed
0,LAG003,2024-03-31,R1,hts_tst_pos must be less than or equal to hts_tst,3407.0 > 3384.0
1,FCT005,2023-02-28,R1,hts_tst_pos must be less than or equal to hts_tst,443.0 > 403.0
2,RIV014,2023-06-30,R1,hts_tst_pos must be less than or equal to hts_tst,1085.0 > 1064.0
3,BEN012,2024-08-01,R1,hts_tst_pos must be less than or equal to hts_tst,615.0 > 572.0
4,NAS999,2024-04-30,R1,hts_tst_pos must be less than or equal to hts_tst,693.0 > 646.0

In [1018]:
# checkijng how many facilities has uses in each of the validation rules
issues["rule_id"].value_counts()

rule_id
R11    3773
R8     3520
R10    2204
R6      135
R1       50
R3       46
R7       44
R5       41
R2       21
R9       17
R4       10
Name: count, dtype: int64

In [1019]:
# Based on the validations we have done across the facility_service_data_2022-2024 we can to a conclusion that rule R11 was the most violated with 3773 issues, followed by R8 with 3520, R10 with 2204, and R6 with 2204

In [1020]:
issues["facility_id"].value_counts().head(10)

facility_id
XXX999    130
NAS999    124
TMP001    112
LAG099    110
RIV001    103
CRS010     96
CRS007     94
AKS005     94
NAS007     94
FCT005     94
Name: count, dtype: int64

In [1021]:
# Above are the top 10 facilities with the most violations

In [1022]:
# From df we get the facility_id and their states and remove all duplicates 
facility_state = (
    df[["facility_id", "state"]].drop_duplicates()
)

In [1023]:
# We then merge the Facility states with the issues with the common column facility_id, because the issues didn't have a state column
issues_with_state = issues.merge(
    facility_state,
    on="facility_id",
    how="left"
)

In [1024]:
# The top 10 states with the most issues
issues_with_state["state"].value_counts().head(10)

state
RIVERS         1714
NASARAWA       1676
KADUNA         1674
AKWA IBOM      1671
LAGOS          1656
CROSS RIVER    1627
BENUE          1616
FCT            1559
Name: count, dtype: int64

In [1025]:
# Converted all the issue validations to a CSV file
issues.to_csv("issues_log", index = False)

In [1026]:
# Imported the hts_age_sex_disaggregation_2024.csv
ds = pd.read_csv("hts_age_sex_disaggregation_2024.csv")
ds.head()

  facility_id report_month     sex age_band hts_tst hts_tst_pos
0      AKS001      2024-01  Female      <15      24           0
1      AKS001      2024-01  Female    15-24      63           0
2      AKS001      2024-01  Female    25-34      63           0
3      AKS001      2024-01  Female    35-49      51         NaN
4      AKS001      2024-01  Female      50+      27           0

In [1027]:
# Standardizing the sex column to just Male and Female
sex = {
    "Female": "Female",
    "female": "Female",
    "F": "Female",
    "f": "Female",
    "Male": "Male",
    "male": "Male",
    "M": "Male",
    "m": "Male"
}

ds["sex"] = ds["sex"].replace(sex)
ds["sex"].unique()

array(['Female', 'Male'], dtype=object)

In [1028]:
# Value count on how many males and females 
ds["sex"].value_counts()

sex
Female    7200
Male      7200
Name: count, dtype: int64

In [1029]:
# value count on the age band 
ds["age_band"].value_counts()

age_band
25-34           2880
35-49           2880
<15             2703
15-24           2700
50+             2700
15 - 24          180
50 and above     180
0-14             177
Name: count, dtype: int64

In [1030]:
# standardizing the age band to just 5 age bands 
age_map = {
    "<15": "0-14",
    "0-14": "0-14",
    "15-24": "15-24",
    "15 - 24": "15-24",
    "50+": "50+",
    "50 and above": "50+"
}

ds["age_band"] = ds["age_band"].replace(age_map)

In [1031]:
# Checking the age band 
ds["age_band"].unique()

array(['0-14', '15-24', '25-34', '35-49', '50+'], dtype=object)

In [1032]:
# created a new column age_sex 
ds["age_sex"] = (
    ds["sex"] + " " + ds["age_band"]
)

In [1033]:
# checking the age_sex column, below i checked my hts_tst data type and it said it was an object so i had comeup and change the hts type to numeric so eveything i had previously worked on would be in a numberic format

ds["hts_tst"] = pd.to_numeric(ds["hts_tst"], errors="coerce")

In [1034]:
# making a pivot wide table with the facility id and report month as index and the columns as age_sex values, the values under the age_sex are gotten from the sum of the hts_tst  
wide = ds.pivot_table(
    index=["facility_id", "report_month"],
    columns="age_sex",
    values=  "hts_tst",
    aggfunc="sum",
    fill_value=0
).reset_index()

In [1035]:
# Checking the wide table
wide.head()

age_sex,facility_id,report_month,Female 0-14,Female 15-24,Female 25-34,Female 35-49,Female 50+,Male 0-14,Male 15-24,Male 25-34,Male 35-49,Male 50+
0,AKS001,2024-01,24.0,63.0,63.0,51.0,27.0,14.0,48.0,53.0,34.0,16.0
1,AKS001,2024-02,32.0,113.0,123.0,91.0,37.0,25.0,89.0,90.0,55.0,26.0
2,AKS001,2024-03,33.0,99.0,93.0,76.0,31.0,25.0,57.0,77.0,54.0,26.0
3,AKS001,2024-04,30.0,86.0,117.0,81.0,32.0,23.0,67.0,84.0,53.0,23.0
4,AKS001,2024-05,34.0,110.0,117.0,90.0,37.0,30.0,81.0,80.0,65.0,23.0

In [1036]:
# checking the pivot wide columns 
wide.columns

Index(['facility_id', 'report_month', 'Female 0-14', 'Female 15-24',
       'Female 25-34', 'Female 35-49', 'Female 50+', 'Male 0-14', 'Male 15-24',
       'Male 25-34', 'Male 35-49', 'Male 50+'],
      dtype='object', name='age_sex')

In [1037]:
# .melt is used to change back from wide to long, so the age_sex values are no more columns but now rows and the values of the sex_age are now in a column called value 
long_again = wide.melt(
    id_vars=["facility_id", "report_month"],
    var_name="sex_age",
    value_name= "hts_tst"
)
long_again.head()

  facility_id report_month      sex_age  hts_tst
0      AKS001      2024-01  Female 0-14     24.0
1      AKS001      2024-02  Female 0-14     32.0
2      AKS001      2024-03  Female 0-14     33.0
3      AKS001      2024-04  Female 0-14     30.0
4      AKS001      2024-05  Female 0-14     34.0

In [1038]:
# i have to change report_month to pd.to_datetime
ds["report_month"] = pd.to_datetime(ds["report_month"], errors="coerce")

In [1039]:
# then i created a column called year from the report month 
ds["year"] = ds["report_month"].dt.year

In [1040]:
# i grouped the facility and the facility year with the sum of the hts_tst values 
facility_year = (
    ds.groupby(["facility_id", "year"])
    ["hts_tst"].sum().reset_index()
    )
facility_year.head()

  facility_id  year  hts_tst
0      AKS001  2024   7281.0
1      AKS002  2024   3324.0
2      AKS003  2024   7896.0
3      AKS004  2024   2910.0
4      AKS005  2024   1627.0

In [1041]:
facility_year.count()

facility_id    120
year           120
hts_tst        120
dtype: int64

In [1042]:
# From the facility service data file i made sure the report month had a date and time data type
df["report_month"] = pd.to_datetime(df["report_month"])

In [1043]:
# i got the year out from the reprot month using dt.year
df["year"] = df["report_month"].dt.year

In [1044]:
# I made a copy of the column year only containing the 2024 reports 
aggregate_2024 = df[df["year"] == 2024].copy()

In [1060]:
# Checkinng duplicate from the aggregate 2024
duplicates = aggregate_2024[
    aggregate_2024.duplicated(
        subset=["facility_id", "report_month"],
        keep=False
    )
]

In [1065]:
# getting the sum of the hts_tst reprot month from the facility_id and 2024 year 
aggregate_total_2024 = (
    aggregate_2024
    .groupby(["facility_id", "year"], as_index= False)["hts_tst"]
    .sum()
)
aggregate_total_2024.head()

  facility_id  year  hts_tst
0      AKS001  2024   6787.0
1      AKS002  2024   3382.0
2      AKS003  2024   6565.0
3      AKS004  2024   2775.0
4      AKS005  2024   1549.0

In [1047]:
# merging the aggregate total from the facility service data 2024 to the facility year data frame
compare = pd.merge(
    facility_year,
    aggregate_total_2024,
    on=["facility_id", "year"],
    how="outer",
    suffixes=("_disagg", "_agg")
)
compare.head(10)

  facility_id  year  hts_tst_disagg  hts_tst_agg
0      AKS001  2024          7281.0       6787.0
1      AKS002  2024          3324.0       3382.0
2      AKS003  2024          7896.0       6565.0
3      AKS004  2024          2910.0       2775.0
4      AKS005  2024          1627.0       1549.0
5      AKS006  2024          6453.0       6515.0
6      AKS007  2024         13211.0      12471.0
7      AKS008  2024          1142.0       1101.0
8      AKS009  2024          1057.0       1127.0
9      AKS010  2024          7784.0       7259.0

In [1048]:
# calculating the percentage difference between the aggregated hts_tst and the disaggregated hts_tst
compare["pctg_diff"]=(
    abs(
        compare["hts_tst_disagg"] - compare["hts_tst_agg"]
    )/compare["hts_tst_agg"] * 100
)
compare["pctg_diff"].head(10)

0     7.278621
1     1.714962
2    20.274181
3     4.864865
4     5.035507
5      0.95165
6     5.933766
7     3.723887
8      6.21118
9     7.232401
Name: pctg_diff, dtype: Float64

In [ ]:
# i create a column called flag that is true if the pctg_diff is greater than 5
compare["flag"] = (
    compare["pctg_diff"]>5
)
compare["flag"].head(15)

0      True
1     False
2      True
3     False
4      True
5     False
6      True
7     False
8      True
9      True
10    False
11    False
12     True
13    False
14    False
Name: flag, dtype: boolean

In [1059]:
# flag_disagg contains only facilites that pctg_diff is greater that 5%
flag_disagg = compare[compare["pctg_diff"]>5]
flag_disagg.head(10)

   facility_id  year  hts_tst_disagg  hts_tst_agg  pctg_diff  flag
0       AKS001  2024          7281.0       6787.0   7.278621  True
2       AKS003  2024          7896.0       6565.0  20.274181  True
4       AKS005  2024          1627.0       1549.0   5.035507  True
6       AKS007  2024         13211.0      12471.0   5.933766  True
8       AKS009  2024          1057.0       1127.0    6.21118  True
9       AKS010  2024          7784.0       7259.0   7.232401  True
12      AKS013  2024          4954.0       4626.0   7.090359  True
17      BEN003  2024          7245.0       6378.0  13.593603  True
18      BEN004  2024         12729.0      11709.0   8.711248  True
19      BEN005  2024          6966.0       7750.0  10.116129  True

In [1067]:
""" The aggregated data represents the hts_tst from the facility service data and the disaggregated data shows the break down of the aggregated data by facilities, months, age group, and sex. Therefore the sum of the disaggregated should give an approximate value of the aggregate, if they disagree by more than 5%, this indicates discrepancy between the two sources."""

' The aggregated data represents the hts_tst from the facility service data and the disaggregated data shows the break down of the aggregated data by facilities, months, age group, and sex. Therefore the sum of the disaggregated should give an approximate value of the aggregate, if they disagree by more than 5%, this indicates discrepancy between the two sources.'

In [ ]:
# Selected each of the validaton rules that is to be exclude and saved them in a variable, then we grouped the rows together in bad_index
r1_bad = r1(df)
r2_bad = r2(df)
r3_bad = r3(df)
r4_bad = r4(df)
r5_bad = r5(df)


bad_index = (
    r1_bad.index
    .union(r2_bad.index)
    .union(r3_bad.index)
    .union(r4_bad.index)
    .union(r5_bad.index)
)

In [ ]:
# i created a clean_df and removed all the rows that r1-r5 flags out and created a copy of the clean_df for use
clean_df = df.drop(index=bad_index).copy()

In [ ]:
# performed a left merge with the facility master list to keep the facility_id on the clean_df and not on the fm since we're working with the clean_df
clean_df = clean_df.merge(
    fm[["facility_id", "facility_level"]],
    on="facility_id",
    how="left"
)

In [ ]:
# Checking the rows that were removed
print("Original rows:", len(df))
print("Clean rows:", len(clean_df))
print("Excluded rows:", len(bad_index))

Original rows: 4355
Clean rows: 4192
Excluded rows: 163

In [ ]:
# The first indicator: HIV positivity yeild, by state
hts_tst_state = (
    clean_df .groupby("state", as_index=False) .agg( hts_tst=("hts_tst", "sum"), hts_tst_pos=("hts_tst_pos", "sum"))
)

hts_tst_state["hiv_positivity_yield"] = (
    hts_tst_state["hts_tst_pos"] / hts_tst_state["hts_tst"] * 100
)
hts_tst_state

         state   hts_tst  hts_tst_pos  hiv_positivity_yield
0    AKWA IBOM  222634.0       6271.0              2.816731
1        BENUE  390492.0       7821.0              2.002858
2  CROSS RIVER  241468.0       7096.0              2.938692
3          FCT  380130.0      10115.0              2.660932
4       KADUNA  461879.0      14837.0              3.212313
5        LAGOS  509027.0      16461.0              3.233817
6     NASARAWA  425532.0      11805.0              2.774174
7       RIVERS  355060.0      10203.0              2.873599

In [ ]:
# The first indicator: HIV positivity yeild, by year
hts_tst_year = (
    clean_df .groupby("year", as_index=False) .agg( hts_tst=("hts_tst", "sum"), hts_tst_pos=("hts_tst_pos", "sum"))
)

hts_tst_year["hiv_positivity_yield"] = (
    hts_tst_year["hts_tst_pos"] / hts_tst_year["hts_tst"] * 100
)
hts_tst_year

   year    hts_tst  hts_tst_pos  hiv_positivity_yield
0  2022   891767.0      25583.0              2.868799
1  2023   975576.0      27784.0              2.847959
2  2024  1118879.0      31242.0              2.792259

In [1109]:
# The first indicator: HIV positivity yeild, by facility_level
hts_tst_facility_level = (
    clean_df .groupby("facility_level", as_index=False) .agg( hts_tst=("hts_tst", "sum"), hts_tst_pos=("hts_tst_pos", "sum"))
    )

hts_tst_facility_level["hiv_positivity_yield"] = (
    hts_tst_facility_level["hts_tst_pos"] / hts_tst_facility_level["hts_tst"] * 100
)
hts_tst_facility_level

  facility_level    hts_tst  hts_tst_pos  hiv_positivity_yield
0        Primary   588836.0      16885.0              2.867522
1      Secondary   956321.0      21722.0              2.271413
2       Tertiary  1327267.0      42649.0              3.213295

In [ ]:
# Second indicator: By year 2024
facility_2024 = clean_df[clean_df["year"]== 2024].copy()

In [ ]:
# Second indicator: calculating people that have been diagnosed but has not stated treatment 
linkage = (
    facility_2024.groupby("facility_id", as_index=False).agg(
        hts_tst_pos=("hts_tst_pos", "sum"), tx_new=("tx_new", "sum")
    )
)
# Zero causes division errors
linkage["linkage_proxy"] = (
        linkage["tx_new"] / linkage["hts_tst_pos"].replace(0, pd.NA)
    )
linkage

    facility_id  hts_tst_pos  tx_new  linkage_proxy
0        AKS001         54.0    38.0       0.703704
1        AKS002         20.0    11.0           0.55
2        AKS003        183.0   146.0       0.797814
3        AKS004         82.0    71.0       0.865854
4        AKS005         14.0     8.0       0.571429
..          ...          ...     ...            ...
119      RIV013        224.0   193.0       0.861607
120      RIV014        112.0    86.0       0.767857
121      RIV015        277.0   230.0       0.830325
122      TMP001        164.0   144.0       0.878049
123      XXX999        380.0   325.0       0.855263

[124 rows x 4 columns]

In [1130]:
# sorting the facilities in ascending order to get the 10 lowest facilites below 0.8
linkage_low = linkage.sort_values("linkage_proxy")

linkage_low.head(10)

    facility_id  hts_tst_pos  tx_new  linkage_proxy
107      RIV001          5.0     2.0            0.4
44       CRS015         17.0     8.0       0.470588
39       CRS010         16.0     8.0            0.5
98       NAS008         23.0    12.0       0.521739
82       LAG008         26.0    14.0       0.538462
7        AKS008         24.0    13.0       0.541667
1        AKS002         20.0    11.0           0.55
4        AKS005         14.0     8.0       0.571429
92       NAS002         31.0    19.0       0.612903
42       CRS013         46.0    29.0       0.630435

In [ ]:
# Third indicator: Treatment continuity, we got only the rows that are 2024 in the year column and made a copy
tx_2024 = clean_df[
    clean_df["year"] == 2024
].copy()

tx_2024 = tx_2024.sort_values(
    ["facility_id", "report_month"]
)

In [ ]:
# I grouped them by their facility id's got the first and last tx_curr, and the sum of the new and ml tx
treatment_continuity = (
    tx_2024 .groupby("facility_id", as_index=False) .agg(
        first_tx_curr=("tx_curr", "first"),
        last_tx_curr=("tx_curr", "last"),
        tx_new=("tx_new", "sum"),
        tx_ml=("tx_ml", "sum")
    )
)
treatment_continuity

    facility_id  first_tx_curr  last_tx_curr  tx_new  tx_ml
0        AKS001            323           329    38.0     35
1        AKS002            582           528    11.0     67
2        AKS003            383           494   146.0     41
3        AKS004            947           907    71.0    102
4        AKS005           1045           922     8.0    131
..          ...            ...           ...     ...    ...
119      RIV013           2130          2100   193.0    220
120      RIV014            664           654    86.0     97
121      RIV015           2311         21820   230.0    346
122      TMP001            168           784   144.0    236
123      XXX999           1345          2090   325.0    316

[124 rows x 5 columns]

In [ ]:
# and found the net change between the tx_curr for each facility 
treatment_continuity["net_change"] = (
    treatment_continuity["last_tx_curr"] - treatment_continuity["first_tx_curr"]
)

In [ ]:
# I then for the facilities that were greater than 0 i'd create column cohort direcion and give them growing and for the ones that were less than 0 shrinking  
treatment_continuity["cohort_direction"] = (
    treatment_continuity["net_change"]
    .apply( lambda x: "Growing" if x > 0 else "Shrinking" if x < 0 else "No change"
    )
)
treatment_continuity.head(10)

,facility_id,first_tx_curr,last_tx_curr,tx_new,tx_ml,net_change,cohort_direction
0,AKS001,323,329,38.0,35,6,Growing
1,AKS002,582,528,11.0,67,-54,Shrinking
2,AKS003,383,494,146.0,41,111,Growing
3,AKS004,947,907,71.0,102,-40,Shrinking
4,AKS005,1045,922,8.0,131,-123,Shrinking
5,AKS006,430,525,167.0,61,95,Growing
6,AKS007,5481,4996,171.0,699,-485,Shrinking
7,AKS008,84,95,13.0,3,11,Growing
8,AKS009,222,239,35.0,18,17,Growing
9,AKS010,1601,1559,114.0,163,-42,Shrinking

In [ ]:
# Then i got only the facilites that the net change is greater than 0
growing = treatment_continuity[
    treatment_continuity["net_change"].gt(0) 
]
growing.head(10)

,facility_id,first_tx_curr,last_tx_curr,tx_new,tx_ml,net_change,cohort_direction
0,AKS001,323,329,38.0,35,6,Growing
2,AKS003,383,494,146.0,41,111,Growing
5,AKS006,430,525,167.0,61,95,Growing
7,AKS008,84,95,13.0,3,11,Growing
8,AKS009,222,239,35.0,18,17,Growing
10,AKS011,329,339,51.0,44,10,Growing
11,AKS012,1109,1397,415.0,114,288,Growing
12,AKS013,634,729,131.0,45,95,Growing
13,AKS014,615,618,75.0,69,3,Growing
18,BEN004,391,426,75.0,46,35,Growing

In [ ]:
# And this for the ones that are less then zero shrinking
shrinking = treatment_continuity[
    treatment_continuity["net_change"].lt(0) 
]
shrinking.head(10)

,facility_id,first_tx_curr,last_tx_curr,tx_new,tx_ml,net_change,cohort_direction
1,AKS002,582,528,11.0,67,-54,Shrinking
3,AKS004,947,907,71.0,102,-40,Shrinking
4,AKS005,1045,922,8.0,131,-123,Shrinking
6,AKS007,5481,4996,171.0,699,-485,Shrinking
9,AKS010,1601,1559,114.0,163,-42,Shrinking
14,AKS015,2432,2431,271.0,318,-1,Shrinking
15,BEN001,1779,1650,73.0,276,-129,Shrinking
16,BEN002,4444,4413,457.0,494,-31,Shrinking
17,BEN003,2411,2294,200.0,298,-117,Shrinking
21,BEN007,1925,1736,48.0,262,-189,Shrinking

In [1182]:
# I created a quater column
clean_df["quarter"] = (
    "Q" + clean_df["report_month"].dt.quarter.astype(str)
)
clean_df["quarter"].head()

0    Q4
1    Q2
2    Q1
3    Q1
4    Q1
Name: quarter, dtype: object

In [1191]:
# groupd the vl_eligible and vl_result by state and quater 
vl_coverage = (
    clean_df.groupby(["state", "quarter"], as_index=False) .agg(
        vl_eligible=("vl_eligible", "sum"),vl_result_received=("vl_result_received", "sum")
    )
)
vl_coverage.head(10)

         state quarter  vl_eligible  vl_result_received
0    AKWA IBOM      Q1     116365.0             80752.0
1    AKWA IBOM      Q2     112007.0             88011.0
2    AKWA IBOM      Q3     120006.0             88489.0
3    AKWA IBOM      Q4     113561.0             88585.0
4        BENUE      Q1     154305.0            114289.0
5        BENUE      Q2     165719.0            126696.0
6        BENUE      Q3     157643.0            116137.0
7        BENUE      Q4     163975.0            121894.0
8  CROSS RIVER      Q1     126519.0             91979.0
9  CROSS RIVER      Q2     127114.0            100565.0

In [1183]:
# Calculated for the vl_coverage 
vl_coverage["vl_coverage"] = (
   ( vl_coverage["vl_result_received"] / vl_coverage["vl_eligible"].replace(0, pd.NA)) * 100
)
vl_coverage.head(10)

         state quarter  vl_eligible  vl_result_received  vl_coverage
0    AKWA IBOM      Q1     116365.0             80752.0    69.395437
1    AKWA IBOM      Q2     112007.0             88011.0    78.576339
2    AKWA IBOM      Q3     120006.0             88489.0    73.737146
3    AKWA IBOM      Q4     113561.0             88585.0    78.006534
4        BENUE      Q1     154305.0            114289.0    74.066945
5        BENUE      Q2     165719.0            126696.0    76.452308
6        BENUE      Q3     157643.0            116137.0    73.670889
7        BENUE      Q4     163975.0            121894.0    74.336942
8  CROSS RIVER      Q1     126519.0             91979.0    72.699753
9  CROSS RIVER      Q2     127114.0            100565.0    79.114024

In [1188]:
# Fifth indicator: Viral load suppression by state 
vl_suppression = (
    clean_df .groupby("state", as_index=False) .agg(
        vl_result_received=("vl_result_received", "sum"), vl_suppressed=("vl_suppressed", "sum")
    )
)
vl_suppression.head(10)

         state  vl_result_received  vl_suppressed
0    AKWA IBOM            345837.0       315006.0
1        BENUE            479016.0       428914.0
2  CROSS RIVER            386890.0       342264.0
3          FCT            650990.0       593052.0
4       KADUNA            545879.0       486570.0
5        LAGOS            762701.0       676035.0
6     NASARAWA            545136.0       492082.0
7       RIVERS            584266.0       519101.0

In [1189]:
# Simple vl_suppression calculation
vl_suppression["vl_suppression"] = (
    (vl_suppression["vl_suppressed"] / vl_suppression["vl_result_received"].replace(0, pd.NA)) * 100
)
vl_suppression.head(10)

         state  vl_result_received  vl_suppressed  vl_suppression
0    AKWA IBOM            345837.0       315006.0       91.085107
1        BENUE            479016.0       428914.0       89.540642
2  CROSS RIVER            386890.0       342264.0       88.465455
3          FCT            650990.0       593052.0       91.100017
4       KADUNA            545879.0       486570.0       89.135138
5        LAGOS            762701.0       676035.0       88.636963
6     NASARAWA            545136.0       492082.0        90.26775
7       RIVERS            584266.0       519101.0        88.84669

In [1228]:
# Sixth indicator: PMTCT positivity
pmtct_positive = (
    clean_df.groupby(
        "facility_id", as_index=False
    ).agg(
        pmtct_stat= ("pmtct_stat", "sum"),
        pmtct_stat_pos= ("pmtct_stat_pos", "sum")
    )
)
pmtct_positive.head(10)

  facility_id  pmtct_stat  pmtct_stat_pos
0      AKS001      3628.0              23
1      AKS002      1793.0              12
2      AKS003      3715.0              54
3      AKS004      1425.0              37
4      AKS005       821.0               6
5      AKS006      3325.0              68
6      AKS007      6353.0              52
7      AKS008       600.0               7
8      AKS009       584.0               7
9      AKS010      4161.0              47

In [ ]:
# Calculation for the ppmtct positivity 
pmtct_positive["pmtct_positivity"] =(
    (pmtct_positive["pmtct_stat_pos"]/ pmtct_positive["pmtct_stat"].replace(0, pd.NA)) * 100
)
pmtct_positive.head(10)

  facility_id  pmtct_stat  pmtct_stat_pos  pmtct_positivity
0      AKS001      3628.0              23          0.633958
1      AKS002      1793.0              12          0.669269
2      AKS003      3715.0              54          1.453567
3      AKS004      1425.0              37          2.596491
4      AKS005       821.0               6          0.730816
5      AKS006      3325.0              68          2.045113
6      AKS007      6353.0              52          0.818511
7      AKS008       600.0               7          1.166667
8      AKS009       584.0               7           1.19863
9      AKS010      4161.0              47          1.129536

In [ ]:
# Sixth indicator: Pmtct art 
pmtct_art = (
    clean_df.groupby(
        "facility_id", as_index=False
    ).agg(
        pmtct_art= ("pmtct_art", "sum"),
        pmtct_stat_pos= ("pmtct_stat_pos", "sum")
    )
)
pmtct_art.head(10)

  facility_id  pmtct_art  pmtct_stat_pos
0      AKS001          7              23
1      AKS002          1              12
2      AKS003         26              54
3      AKS004         15              37
4      AKS005          0               6
5      AKS006         40              68
6      AKS007         25              52
7      AKS008          1               7
8      AKS009          1               7
9      AKS010         22              47

In [1241]:
# calculation for the pmtct art
pmtct_art["pmtct_artt"] =(
    (pmtct_art["pmtct_art"]/ pmtct_art["pmtct_stat_pos"].replace(0, pd.NA)) * 100
)
pmtct_art.head()

  facility_id  pmtct_art  pmtct_stat_pos  pmtct_artt
0      AKS001          7              23   30.434783
1      AKS002          1              12    8.333333
2      AKS003         26              54   48.148148
3      AKS004         15              37   40.540541
4      AKS005          0               6         0.0

In [1233]:
# Seventh indicator: reporting completeness
clean_df = clean_df.merge(
    fm[["facility_id", "art_start_date"]],
    on="facility_id",
    how="left"
)

In [1235]:
clean_df["art_start_date"] = pd.to_datetime(
    clean_df["art_start_date"]
)

In [1238]:
clean_df["expected_report"] = (
    clean_df["report_month"].dt.to_period("M")
    >= clean_df["art_start_date"].dt.to_period("M")
)
clean_df["expected_report"].head()

0    True
1    True
2    True
3    True
4    True
Name: expected_report, dtype: bool

In [ ]:
completeness = (
    clean_df .groupby(["state", "year", "month"], as_index=False)
    .agg( reports_received=("facility_id", "nunique"),  
         reports_expected=("expected_report", "sum")
    )
)
completeness.head()

       state  year  month  reports_received  reports_expected
0  AKWA IBOM  2022      1                15                12
1  AKWA IBOM  2022      2                14                13
2  AKWA IBOM  2022      3                15                13
3  AKWA IBOM  2022      4                15                15
4  AKWA IBOM  2022      5                14                13

In [ ]:
completeness["reporting_completeness"] = (
    completeness["reports_received"] / completeness["reports_expected"].replace(0, pd.NA)
    * 100
).format("{:.2f}")
completeness.head()

,state,year,month,reports_received,reports_expected,reporting_completeness
0,AKWA IBOM,2022,1,15,12,125.000000
1,AKWA IBOM,2022,2,14,13,107.692308
2,AKWA IBOM,2022,3,15,13,115.384615
3,AKWA IBOM,2022,4,15,15,100.000000
4,AKWA IBOM,2022,5,14,13,107.692308